# Trino's native Ranger access control plugin.
# https://trino.io/docs/current/security/ranger-access-control.html
access-control.name=ranger
ranger.service.name=trino-demo
ranger.plugin.config.resource=/etc/trino/ranger/ranger-trino-security.xml,/etc/trino/ranger/ranger-trino-audit.xml
